const brands = [
  {
    _id: "6412eae89c2275a25d09541d",
    products: [],
    name: "Urban Kitchen",
    description:
      "Urban Kitchen specializes in authentic Indian thalis with a modern twist. We offer traditional recipes with fresh ingredients.",
    email: "contact@urbankitchen.com",
    website: "urbankitchen.com",
    location: "Mumbai, Maharashtra",
    phone: "9876543210",
    status: "active",
    logo: "https://i.ibb.co/Ydf3C1H/brand-1.png",
  },
  {
    _id: "641522d9cd2724817c1c7c38",
    products: [],
    name: "Gujarat Express",
    description:
      "Authentic Gujarati cuisine served in traditional thali style. Experience the flavors of Gujarat with our special recipes.",
    email: "info@gujaratexpress.com",
    website: "gujaratexpress.com",
    location: "Ahmedabad, Gujarat",
    phone: "9876543211",
    status: "active",
    logo: "https://i.ibb.co/GTzWqnP/brand-2.png",
  },
  {
    _id: "64153eb3707ca6a96638c13b",
    products: [],
    name: "South Spice",
    description:
      "Traditional South Indian thalis with authentic taste. From dosas to sambar, we serve the best of South India.",
    email: "hello@southspice.com",
    website: "southspice.com",
    location: "Chennai, Tamil Nadu",
    phone: "9876543212",
    status: "active",
    logo: "https://i.ibb.co/YPzHpCD/brand-3.png",
  },
  {
    _id: "6415479cfba1a43da8287e20",
    products: [],
    name: "Punjab Palace",
    description:
      "Rich and flavorful Punjabi thalis with butter naan, dal makhani, and more. Experience the royal taste of Punjab.",
    email: "contact@punjabpalace.com",
    website: "punjabpalace.com",
    location: "Amritsar, Punjab",
    phone: "9876543213",
    status: "active",
    logo: "https://i.ibb.co/n3Wktzh/brand-4.png",
  },
  {
    _id: "64154ee693b3f0f2c7ec7ff8",
    products: [],
    name: "Bengal Flavors",
    description:
      "Authentic Bengali cuisine with fish curry, rosogolla, and traditional sweets. Taste the richness of Bengal.",
    email: "info@bengalflavors.com",
    website: "bengalflavors.com",
    location: "Kolkata, West Bengal",
    phone: "9876543214",
    status: "active",
    logo: "https://i.ibb.co/xqTCvsL/brand-5.png",
  },
  {
    _id: "6415545493b3f0f2c7ec7ffa",
    products: [],
    name: "Royal Feast",
    description:
      "Premium dining experience with luxury thalis. We serve gold-standard meals with royal presentation.",
    email: "reservations@royalfeast.com",
    website: "royalfeast.com",
    location: "New Delhi, Delhi",
    phone: "9876543215",
    status: "active",
    logo: "https://i.ibb.co/SfBRy61/brand-6.png",
  },
  {
    _id: "6415796b0bb49c3eb913bd50",
    products: [],
    name: "Quick Bites",
    description:
      "Fast and fresh mini thalis for busy professionals. Quick service without compromising on taste.",
    email: "order@quickbites.com",
    website: "quickbites.com",
    location: "Bangalore, Karnataka",
    phone: "9876543216",
    status: "active",
    logo: "https://i.ibb.co/LNymxGk/brand-7.png",
  },
  {
    _id: "641feafc19436d47078261a3",
    name: "Pure Veg Kitchen",
    description:
      "100% vegetarian and Jain thalis. We specialize in pure veg cuisine with no onion and garlic options.",
    email: "contact@purevegkitchen.com",
    website: "purevegkitchen.com",
    location: "Jaipur, Rajasthan",
    phone: "9876543217",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/mCqwRnT/brand-8.png",
  },
  {
    _id: "64200b8221162f8b15beae3c",
    name: "Family Feast",
    description:
      "Large family packs and party thalis. Perfect for family gatherings and celebrations.",
    email: "orders@familyfeast.com",
    website: "familyfeast.com",
    location: "Hyderabad, Telangana",
    phone: "9876543218",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/GTzWqnP/brand-2.png",
  },
  {
    _id: "642508be253d81bc860d4d24",
    name: "Desert Delight",
    description:
      "Authentic Rajasthani thalis with dal baati churma and traditional desert cuisine.",
    email: "info@desertdelight.com",
    website: "desertdelight.com",
    location: "Jodhpur, Rajasthan",
    phone: "9876543219",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/n3Wktzh/brand-4.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2130",
    name: "Mumbai Express",
    description:
      "Maharashtrian specialties including vada pav, puran poli, and authentic Mumbai street food in thali format.",
    email: "hello@mumbaiexpress.com",
    website: "mumbaiexpress.com",
    location: "Mumbai, Maharashtra",
    phone: "9876543220",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/mCqwRnT/brand-8.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2131",
    name: "Northeast Kitchen",
    description:
      "Exotic Northeast Indian cuisine with bamboo shoot curry, fish preparations, and unique regional flavors.",
    email: "contact@northeastkitchen.com",
    website: "northeastkitchen.com",
    location: "Guwahati, Assam",
    phone: "9876543221",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/YPzHpCD/brand-3.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2132",
    name: "Kashmir Valley",
    description:
      "Royal Kashmiri cuisine with rogan josh, yakhni, and traditional wazwan preparations.",
    email: "info@kashmirvalley.com",
    website: "kashmirvalley.com",
    location: "Srinagar, Kashmir",
    phone: "9876543222",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/xqTCvsL/brand-5.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2133",
    name: "Green Garden",
    description:
      "Vegan and health-focused thalis with organic ingredients. Perfect for health-conscious diners.",
    email: "health@greengarden.com",
    website: "greengarden.com",
    location: "Pune, Maharashtra",
    phone: "9876543223",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/SfBRy61/brand-6.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2134",
    name: "Fit Kitchen",
    description:
      "Keto, low-carb, and protein-rich thalis for fitness enthusiasts. Healthy eating without compromising taste.",
    email: "nutrition@fitkitchen.com",
    website: "fitkitchen.com",
    location: "Gurgaon, Haryana",
    phone: "9876543224",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/LNymxGk/brand-7.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2135",
    name: "Happy Meals",
    description:
      "Kids-friendly thalis with fun presentations and nutritious ingredients. Making healthy eating fun for children.",
    email: "kids@happymeals.com",
    website: "happymeals.com",
    location: "Noida, Uttar Pradesh",
    phone: "9876543225",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/Ydf3C1H/brand-1.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2136",
    name: "Business Bites",
    description:
      "Executive lunch thalis with quick service for corporate professionals. Premium quality meals delivered fast.",
    email: "corporate@businessbites.com",
    website: "businessbites.com",
    location: "Mumbai, Maharashtra",
    phone: "9876543226",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/GTzWqnP/brand-2.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2137",
    name: "Night Owl Kitchen",
    description:
      "Late-night thali delivery service. Perfect for midnight cravings and late-working professionals.",
    email: "night@nightowlkitchen.com",
    website: "nightowlkitchen.com",
    location: "Bangalore, Karnataka",
    phone: "9876543227",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/YPzHpCD/brand-3.png",
  },
  {
    _id: "643134d4e2c1bd22cebb2138",
    name: "Muscle Kitchen",
    description:
      "High-protein thalis for gym-goers and athletes. Build muscle with our specially designed meal plans.",
    email: "protein@musclekitchen.com",
    website: "musclekitchen.com",
    location: "Chennai, Tamil Nadu",
    phone: "9876543228",
    status: "active",
    products: [],
    logo: "https://i.ibb.co/n3Wktzh/brand-4.png",
  }
];

module.exports = brands;